# Generated by Django 5.1 on 2024-08-13 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GoodsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Товар")),
                ("priority", models.IntegerField(verbose_name="Приоритет")),
            ],
        ),
        migrations.CreateModel(
            name="UsersModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Имя")),
                (
                    "vote_status",
                    models.CharField(
                        choices=[("NOT_VOTED", "not_voted"), ("VOTED", "voted")],
                        max_length=50,
                        verbose_name="Статус голосования",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MatrixModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.IntegerField(verbose_name="Результат голосования")),
                (
                    "x_coordinate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="x_matrices",
                        to="add_product.goodsmodel",
                        verbose_name="Первый товар",
                    ),
                ),
                (
                    "y_coordinate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="y_matrices",
                        to="add_product.goodsmodel",
                        verbose_name="Второй товар",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="goodsmodel",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="add_product.usersmodel",
                verbose_name="Пользователь",
            ),
        ),
    ]
