# Generated by Django 5.1 on 2024-08-15 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("add_product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersmodel",
            name="last_vote_pair",
            field=models.IntegerField(default=1, verbose_name="Пара для голосования"),
        ),
        migrations.CreateModel(
            name="PairModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "good1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="good1_pairs",
                        to="add_product.goodsmodel",
                    ),
                ),
                (
                    "good2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="good2_pairs",
                        to="add_product.goodsmodel",
                    ),
                ),
            ],
        ),
    ]
