# Generated by Django 5.1 on 2024-08-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("add_product", "0002_usersmodel_last_vote_pair_pairmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goodsmodel",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="Товар"),
        ),
        migrations.AlterField(
            model_name="matrixmodel",
            name="value",
            field=models.IntegerField(default=0, verbose_name="Результат голосования"),
        ),
        migrations.AlterField(
            model_name="usersmodel",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="Имя"),
        ),
    ]
